sudo: required

services:
    - docker

language: bash

before_script:
    - make
    - docker-compose build
    - docker-compose up -d
    - docker ps

script:
    - while ! nc -vz -w 5 0.0.0.0 443  >/dev/null; do sleep 1; done
    - while ! nc -vz -w 5 0.0.0.0 29418 >/dev/null; do sleep 1; done
