version: '2.1'
services:
    db:
        image: mariadb:5.5
        container_name: mysql
        restart: on-failure:2
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/mysql:/etc/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=gerrit
            - MYSQL_PASSWORD=GERRIT_PASS
            - MYSQL_DATABASE=reviewdb
        env_file:
            - /etc/mysql/mysql_docker.env
        ports:
            - 3306:3306
    ldap:
        image: dinkel/openldap:latest
        container_name: openldap
        restart: on-failure:2
        volumes:
            - /etc/ldap:/etc/ldap
            - /var/lib/ldap:/var/lib/ldap
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - SLAPD_PASSWORD=password
            - SLAPD_CONFIG_PASSWORD=password
        env_file:
            - /etc/openldap/openldap_docker.env
        ports:
            - 389:389
            - 636:636
    ldap-admin:
        image: osixia/phpldapadmin
        container_name: ldap_phpldapadmin
        ports:
            - 6443:443
        links:
            - ldap:ldap
        depends_on:
            - ldap
        environment:
            - PHPLDAPADMIN_LDAP_HOSTS=ldap
    gerrit:
        build: ./gerrit/alpine
        image: ecc/gerrit:latest
        container_name: gerrit
        restart: on-failure:2
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /etc/gerrit:/var/gerrit/review_site
            - /root/.ssh/:/root/.ssh/
        environment:
            - DATABASE_TYPE=mysql
            - DATABASE_HOSTNAME=db
            - DATABASE_DATABASE=reviewdb
            - DATABASE_USERNAME=gerrit
            - DATABASE_PASSWORD=GERRIT_PASS
        external_links:
            - db:mysql
            - ldap:openldap
        depends_on:
            - db
            - ldap
        ports:
            - 443:443
            - 29418:29418
    
    influxdb_volume:
        image: busybox
        volumes: 
            - /opt/influxdb/data:/data
           
    influxdb:
        image: influxdb/influxdb
        container_name: influxdb
        restart: on-failure:2
        ports:
           - 8083:8083
           - 8086:8086
        expose:
           - 8090
           - 8099
        depends_on:
           - influxdb_volume
        volumes_from:
           - influxdb_volume

    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        restart: always
        command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
        volumes:
           - /:/rootfs:ro
           - /var/run:/var/run:rw
           - /sys:/sys:ro
           - /var/lib/docker/:/var/lib/docker:ro
        links:
           - influxdb:influxdb
        ports:
           - 8080:8080

    grafana:
        image: grafana/grafana:2.6.0
        restart: always
        links:
            - influxdb:influxdb
        ports:
            - "3000:3000"
        environment:
            - HTTP_USER=admin
            - HTTP_PASS=admin
            - INFLUXDB_HOST=influxdb
            - INFLUXDB_PORT=8086
            - INFLUXDB_NAME=cadvisor
            - INFLUXDB_USER=root
            - INFLUXDB_PASS=root 
